# Generated by Django 4.2.1 on 2023-06-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_alter_post_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("draft", "Draft")],
                default="active",
                max_length=10,
            ),
        ),
    ]
